# Generated by Django 5.1.1 on 2025-04-25 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
