# Generated by Django 5.1.1 on 2025-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_temoignage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTemoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=5)),
                ('fichier', models.FileField(upload_to='temoignages_media/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
