# Generated by Django 5.1.1 on 2025-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mediatemoignage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='formation',
            field=models.CharField(max_length=100),
        ),
    ]
