# Generated by Django 5.1.1 on 2025-05-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_mediatemoignage_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='collaborateurs/')),
                ('poste', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
