# Generated by Django 5.1.1 on 2025-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_videopublicitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopublicitaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videopublicitaire',
            name='lien_action',
            field=models.URLField(blank=True, help_text="Lien du bouton (ex: lien d'inscription)", null=True),
        ),
    ]
