# Generated by Django 5.1.1 on 2025-05-06 13:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_videopublicitaire_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('fichier', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
            ],
        ),
        migrations.AlterField(
            model_name='mediatemoignage',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10),
        ),
    ]
