# Generated by Django 5.1.1 on 2025-05-06 14:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_video_alter_mediatemoignage_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopublicitaire',
            name='video',
        ),
        migrations.AddField(
            model_name='videopublicitaire',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
