# Generated by Django 5.1.1 on 2025-05-06 17:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_videopublicitaire_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopublicitaire',
            name='fichier',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videopublicitaire',
            name='lien_action',
            field=models.URLField(blank=True, help_text='Lien du bouton (ex: inscription)', null=True),
        ),
    ]
