# Generated by Django 5.1.1 on 2025-05-15 15:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_service_prix_service_contact_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='photo',
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
