# Generated by Django 5.1.1 on 2025-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_collaborateur_photo_collaborateur_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='media/')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=5)),
            ],
        ),
    ]
