# Generated by Django 5.1.1 on 2025-08-25 13:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
