# Generated by Django 5.1.1 on 2025-08-23 08:36

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
        migrations.AddField(
            model_name='media',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='media',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='media',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
