# Generated by Django 5.1.1 on 2025-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_media_fichier_alter_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('sport', 'Équipements sportifs'), ('autres', 'Autres')], default='autres', max_length=20),
        ),
    ]
