# Generated by Django 5.1.1 on 2025-08-23 09:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_media_fichier_remove_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='date_upload',
        ),
        migrations.RemoveField(
            model_name='media',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
        migrations.AddField(
            model_name='media',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
