# Generated by Django 5.1.1 on 2025-08-23 09:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_media_date_upload_remove_media_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='media'),
        ),
    ]
