# Generated by Django 5.1.1 on 2025-10-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('sport', 'Équipements sportifs'), ('immobilier', 'Immobilier'), ('fast food', 'Fast food'), ('construction', 'Construction'), ('lunetterie', 'Lunetterie'), ('vêtements', 'Vêtements'), ('cosmétique', 'Cosmetique'), ('autres', 'Autres')], default='autres', max_length=20),
        ),
    ]
