# Generated by Django 5.1.1 on 2025-08-25 12:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_media_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
