# Generated by Django 5.1.1 on 2025-08-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_media_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='fichier',
        ),
    ]
